version: '3'
services:
   neuropythy_tutorials:
      container_name: neuropythy-tutorials
      build: .
      command: notebook
      ports:
         - "8888:8888"
      environment:
         - HCP_CREDENTIALS="$HCP_CREDENTIALS"
         - HCP_SUBJECTS_DIR="/data/hcp/subjects"
         - SUBJECTS_DIR="/data/freesurfer_subjects"
         - NPYTHY_DATA_CACHE_ROOT="/data/cache"
      volumes:
         - "$PWD/tutorials:/home/jovyan/tutorials"
